name: Build And Release Latest

on:
    workflow_dispatch:

jobs:
    build-and-release:
        runs-on: ubuntu-22.04
        permissions:
            contents: write
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - uses: awalsh128/cache-apt-pkgs-action@latest
              with:
                  packages: libwebkit2gtk-4.1-dev libgtk-layer-shell-dev pkg-config
                  version: 1.0
            - uses: actions/setup-node@v4
            - name: Install dependencies
              run: npm ci
            - name: Build frontend
              run: npm run build
            - name: Download mikami
              run: |
                  wget https://github.com/HumXC/mikami/releases/download/latest/mikami
                  chmod +x mikami
            - name: Bundle frontend
              run: ./mikami bundle ./dist mika-shell HumXC/mika-shell

            - name: Delete Old Releases
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tags=$(gh release list --json tagName --jq '.[].tagName' | grep latest || true)
                  echo "$tags" | xargs --no-run-if-empty -I {} gh release delete {} --yes
                  echo "$tags" | xargs --no-run-if-empty -I {} gh api --method DELETE /repos/${{ github.repository }}/git/refs/tags/{}
                  sleep 5

            - name: Get Latest Commit Hash
              id: commit
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag_name: latest
                  name: "Latest Release (${{ env.sha_short }})"
                  body: "自动发布于 commit: ${{ env.sha_short }}"
                  draft: false
                  prerelease: false
                  files: mika-shell
